# Generated by Django 5.1 on 2024-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=10000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=150)),
                ('formation', models.CharField(max_length=150)),
                ('definition_de_la_formation', models.CharField(max_length=150)),
                ('programme1', models.CharField(max_length=150)),
                ('programme2', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('a_propos_de_moi', models.TextField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo/ ')),
            ],
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=10000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
