# Generated by Django 5.1 on 2024-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0002_alter_certificate_lien_alter_portofolio_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='cv',
            field=models.FileField(upload_to='cv/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/%Y/%m/%d '),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
