# Generated by Django 5.1 on 2024-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0004_alter_personne_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(upload_to='doc/%Y/%m/%d '),
        ),
    ]
