# Generated by Django 5.1 on 2024-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0007_education_annee_debut_education_annee_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d '),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
