# Generated by Django 5.1 on 2024-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0008_alter_certificate_photo_alter_personne_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='lien',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificat_pdf',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
