# Generated by Django 5.1 on 2024-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0010_alter_personne_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
