# Generated by Django 5.1 on 2024-09-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0011_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
