# Generated by Django 5.1 on 2024-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portof_App', '0012_rename_adress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='numero1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='numero2',
            field=models.CharField(max_length=50),
        ),
    ]
